version: '2'

#volumes:
#  data_st2conf:
#    external:
#      name: 
#  data_st2packs:
#    external:
#      name: 
#  data_mistralconf:
#    external:
#      name: 
#  data_st2web:
#    external:
#      name: 

services:
  st2api:
    image: rancher-m.lan/stackstorm/st2api:1.5.1-4_ubuntu_trusty
    links:
      - mongo
      - rabbitmq
    environment:
      # options are: single-host, distributed, and rancher
      - HOST_IP=192.168.50.10
      - ST2_WEB_HOST=192.168.50.10
      - ST2_WEB_PORT=8443
      - CONTAINER_ENV=distributed
      # options are: volume, http-tar, and git
      # export DATASTORE_TYPE=volume
      - DATASTORE_TYPE=http-tar
      - DATASTORE_HTTP_ADDRESS=http://192.168.50.10:8000//st2.tar.gz

  st2auth:
    image: rancher-m.lan/stackstorm/st2auth:1.5.1-4_ubuntu_trusty
    links:
      - st2api
      - mongo
    environment:
      - HOST_IP=192.168.50.10
      - ST2_WEB_HOST=192.168.50.10
      - ST2_WEB_PORT=8443
      - CONTAINER_ENV=distributed
      - DATASTORE_TYPE=http-tar
      - DATASTORE_HTTP_ADDRESS=http://192.168.50.10:8000//st2.tar.gz

  st2stream:
    image: rancher-m.lan/stackstorm/st2stream:1.5.1-4_ubuntu_trusty
    links:
      - mongo
      - rabbitmq
    environment:
      - HOST_IP=192.168.50.10
      - ST2_WEB_HOST=192.168.50.10
      - ST2_WEB_PORT=8443
      - CONTAINER_ENV=distributed
      - DATASTORE_TYPE=http-tar
      - DATASTORE_HTTP_ADDRESS=http://192.168.50.10:8000//st2.tar.gz

  st2notifier:
    image: rancher-m.lan/stackstorm/st2notifier:1.5.1-4_ubuntu_trusty
    links:
      - st2api
      - mongo
      - rabbitmq
    environment:
      - HOST_IP=192.168.50.10
      - ST2_WEB_HOST=192.168.50.10
      - ST2_WEB_PORT=8443
      - CONTAINER_ENV=distributed
      - DATASTORE_TYPE=http-tar
      - DATASTORE_HTTP_ADDRESS=http://192.168.50.10:8000//st2.tar.gz

  st2resultstracker:
    image: rancher-m.lan/stackstorm/st2resultstracker:1.5.1-4_ubuntu_trusty
    links:
      - st2api
      - mongo
      - rabbitmq
    environment:
      - HOST_IP=192.168.50.10
      - ST2_WEB_HOST=192.168.50.10
      - ST2_WEB_PORT=8443
      - CONTAINER_ENV=distributed
      - DATASTORE_TYPE=http-tar
      - DATASTORE_HTTP_ADDRESS=http://192.168.50.10:8000//st2.tar.gz

  st2rulesengine:
    image: rancher-m.lan/stackstorm/st2rulesengine:1.5.1-4_ubuntu_trusty
    links:
      - st2api
      - mongo
      - rabbitmq
    environment:
      - HOST_IP=192.168.50.10
      - ST2_WEB_HOST=192.168.50.10
      - ST2_WEB_PORT=8443
      - CONTAINER_ENV=distributed
      - DATASTORE_TYPE=http-tar
      - DATASTORE_HTTP_ADDRESS=http://192.168.50.10:8000//st2.tar.gz

  st2sensorcontainer:
    image: rancher-m.lan/stackstorm/st2sensorcontainer:1.5.1-4_ubuntu_trusty
    links:
      - st2api
      - mongo
      - rabbitmq
    environment:
      - HOST_IP=192.168.50.10
      - ST2_WEB_HOST=192.168.50.10
      - ST2_WEB_PORT=8443
      - CONTAINER_ENV=distributed
      - DATASTORE_TYPE=http-tar
      - DATASTORE_HTTP_ADDRESS=http://192.168.50.10:8000//st2.tar.gz

  st2garbagecollector:
    image: rancher-m.lan/stackstorm/st2garbagecollector:1.5.1-4_ubuntu_trusty
    links:
      - st2api
      - mongo
      - rabbitmq
    environment:
      - HOST_IP=192.168.50.10
      - ST2_WEB_HOST=192.168.50.10
      - ST2_WEB_PORT=8443
      - CONTAINER_ENV=distributed
      - DATASTORE_TYPE=http-tar
      - DATASTORE_HTTP_ADDRESS=http://192.168.50.10:8000//st2.tar.gz

  st2actionrunner:
    image: rancher-m.lan/stackstorm/st2actionrunner:1.5.1-4_ubuntu_trusty
    links:
      - st2api
      - st2auth
      - mongo
      - rabbitmq
    environment:
      - HOST_IP=192.168.50.10
      - ST2_WEB_HOST=192.168.50.10
      - ST2_WEB_PORT=8443
      - CONTAINER_ENV=distributed
      - DATASTORE_TYPE=http-tar
      - DATASTORE_HTTP_ADDRESS=http://192.168.50.10:8000//st2.tar.gz
  
  st2web:
    image: rancher-m.lan/stackstorm/st2web:1.5.1-1_ubuntu_trusty
    ports:
      - "8443:443"
    links:
      - st2api
      - st2auth 
      - st2stream 
    environment:
      - HOST_IP=192.168.50.10
      - ST2_WEB_HOST=192.168.50.10
      - ST2_WEB_PORT=8443
      - CONTAINER_ENV=distributed
      - DATASTORE_TYPE=http-tar
      - DATASTORE_HTTP_ADDRESS=http://192.168.50.10:8000//st2web.tar.gz

  #st2mistral:
  #  image: stackstorm/st2mistral:
  #  links:
  #    - st2api
  #    - postgres 
    #volumes:
    #  - data_mistralconf:/etc/st2:ro

  ## Client container
  # st2client:
  #   links:
  #     - st2api
  #     - st2auth
  
  ## External Services
  mongo:
    image: mongo
  #postgres:
  #  image: postgres 
  rabbitmq:
    image: rabbitmq

