[template]
#prefix = "/"
src = "st2.conf.tmpl"
dest = "/etc/st2/st2.conf"
owner = "root"
mode = "0644"
keys = [
  "/st2/api/url",
  "/rabbitmq/url",
  "/mongo/address",
  "/mongo/port",
]
#check_cmd = "/usr/sbin/nginx -t -c {{.src}}"
#reload_cmd = "/usr/sbin/service nginx reload"
