FROM quay.io/dennybaa/droneruby:{{ suite }}

# Additional software (needed for RSpec, serverspec)
RUN DEBIAN_FRONTEND=noninteractive && apt-get -y update && \
    apt-get -y install netcat && apt-get -y clean

ADD Gemfile /root/Gemfile

RUN bash -lc "bundle --gemfile=/root/Gemfile"
